name: location_kit
description: Minimal location service for Flutter apps with GPS positioning and distance calculation.
version: 0.3.0
homepage: https://github.com/ZenKitX/LocationKit
repository: https://github.com/ZenKitX/LocationKit
issue_tracker: https://github.com/ZenKitX/LocationKit/issues
documentation: https://github.com/ZenKitX/LocationKit/blob/main/README.md

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Plugin configuration
  plugin:
    platforms:
      android:
        package: com.zenkit.location_kit
        pluginClass: LocationKitPlugin
      ios:
        pluginClass: SwiftLocationKitPlugin
