name: location_kit
description: A location service package for Flutter apps with GPS positioning, permission handling, and distance calculation.
version: 0.2.0
homepage: https://github.com/ZenKitX/LocationKit
repository: https://github.com/ZenKitX/LocationKit
issue_tracker: https://github.com/ZenKitX/LocationKit/issues
documentation: https://github.com/ZenKitX/LocationKit/blob/main/README.md

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
